import React, { useState, useEffect } from 'react';
import { LayoutDashboard, Calendar, User, Filter, Activity, ShieldCheck, Clock, Users, LogOut, ChevronsLeft, ChevronsRight } from 'lucide-react';

import RequestForm from './components/RequestForm';
import ConflictCard from './components/ConflictCard';
import ExplanationReceipt from './components/ExplanationReceipt';
import GanttTimeline from './components/GanttTimeline';
import CorridorMap from './components/CorridorMap';
import Login from './components/Login';
import ProfileModal from './components/ProfileModal';
import NotificationBell from './components/NotificationBell';

import { getDashboard, getLatestPlan, generatePlan, submitBlockRequest } from './api';
import { MAINTENANCE_BLOCKS } from './mockData';

export default function App() {
// --- AUTH STATE ---
  const [user, setUser] = useState(null);
  const [showProfile, setShowProfile] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

// --- NOTIFICATIONS ---
  const [notifications, setNotifications] = useState([]);

  const addNotification = (title, message, type) => {
    const id = Date.now() + Math.random();
    setNotifications((prev) => [
      {
        id,
        title,
        message,
        type,
        read: false,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      },
      ...prev,
    ]);
    return id;
  };

  const markAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
  };

  const handleRequestSubmit = async (data) => {
    try {
        const res = await submitBlockRequest(data);
        addNotification('Request sent', 'Your manual block request was sent for review.', 'sent');
        addNotification('Request processed', res.message || 'Block request submitted successfully.', 'approved');
    } catch (e) {
        addNotification('Request failed', 'Failed to submit block request.', 'error');
    }
  };

// --- STATE ---
  const [activeTab, setActiveTab] = useState('dashboard');
  const [selectedBlockId, setSelectedBlockId] = useState(null);
  const [isResolved, setIsResolved] = useState(false);
  const [filterTask, setFilterTask] = useState('ALL');
  const [activeUsers, setActiveUsers] = useState(142); // Starting number of users
  
  const [blocks, setBlocks] = useState([]);
  const [dashboardMetrics, setDashboardMetrics] = useState({
      active_blocks: 0, conflicts: 0, efficiency: 0, hours_saved: 0, optimizer_status: 'offline'
  });
  const [conflicts, setConflicts] = useState([]);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [explanationData, setExplanationData] = useState(null);

  // --- HACKATHON DEMO TRICK: Simulate live user fluctuation ---
  useEffect(() => {
    const interval = setInterval(() => {
      // Randomly adds or subtracts 1 to 3 users every 5 seconds
      setActiveUsers(prev => prev + (Math.floor(Math.random() * 5) - 2));
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  // Fetch initial data
  const fetchData = async () => {
      try {
          const dash = await getDashboard();
          setDashboardMetrics(dash);
          
          // Normally we'd fetch blocks and conflicts. Since we have the ML generator,
          // we'll load the latest plan.
          const latest = await getLatestPlan();
          if (latest && latest.blocks_generated) {
              setBlocks([]); // Ideally we'd map this, for now keep empty or synthetic
          }
      } catch (e) {
          console.error("API failed", e);
          setDashboardMetrics(prev => ({...prev, optimizer_status: 'offline/error'}));
      }
  };

  useEffect(() => {
      if (user) fetchData();
  }, [user]);

  // --- AUTH GUARD: block the whole app until logged in ---
  if (!user) {
    return <Login onLoginSuccess={(userData) => setUser(userData)} />;
  }

  const displayBlocks = filterTask === 'ALL'
    ? blocks
    : blocks.filter(b => b.id === filterTask);

  const isConflict = conflicts.some(c => c.blockA?.id === selectedBlockId || c.blockB?.id === selectedBlockId);
  const selectedBlockData = blocks.find(b => b.id === selectedBlockId);

  const handleOptimize = async () => {
      setIsOptimizing(true);
      try {
          const result = await generatePlan({ num_tasks: 50 });
          const planBlocks = result.selected_candidates || [];
          
          // Map backend blocks to frontend Gantt structure
          const mappedBlocks = planBlocks.map((c, i) => ({
              id: `B-00${i+1}`,
              title: `Task ${c.task_id} Mega-block`,
              department: 'Engineering',
              sectionId: `SEC-${c.section}`,
              startHour: c.start_hour,
              endHour: c.start_hour + c.duration_hrs,
              status: 'Scheduled',
              type: 'Mega-Block',
              description: `Generated by OR-Tools. Risk covered: ${c.risk_covered.toFixed(2)}`,
              urgency: c.urgency,
          }));
          
          setBlocks(mappedBlocks);
          setConflicts([]);
          setIsResolved(true);
          setExplanationData({
              combinedTasks: ['Task ' + planBlocks[0]?.task_id, 'Task ' + planBlocks[1]?.task_id],
              reasons: ['Tasks optimized by OR-Tools CP-SAT', 'Low predicted train impact', 'Safe resource allocation'],
              hoursSaved: result.selected_candidates.length * 1.5
          });
          fetchData(); // Refresh dashboard
      } catch (e) {
          console.error("Optimization failed", e);
      } finally {
          setIsOptimizing(false);
      }
  };

  return (
    <div className="flex h-screen bg-slate-50 font-sans overflow-hidden text-slate-800">

      {/* SIDEBAR */}
      <div className={`${sidebarCollapsed ? 'w-20' : 'w-64'} bg-slate-900 text-slate-300 flex flex-col shadow-2xl z-20 border-r border-slate-800 shrink-0 transition-all duration-200`}>
        <div className="p-6 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between">
          {sidebarCollapsed ? (
            <Activity className="text-blue-500 mx-auto" size={24} />
          ) : (
            <div>
              <h1 className="text-2xl font-black tracking-wider text-white flex items-center gap-2">
                <Activity className="text-blue-500" size={24} />
                
              </h1>
              <p className="text-blue-400/80 text-[15px] font-bold uppercase tracking-widest mt-1.5">AI Block Planning System</p>
            </div>
          )}
        </div>

        <button
          onClick={() => setSidebarCollapsed((v) => !v)}
          title={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
          className="mx-4 mt-3 flex items-center justify-center gap-2 text-slate-500 hover:text-white hover:bg-slate-800 rounded-md py-1.5 transition-colors"
        >
          {sidebarCollapsed ? <ChevronsRight size={16} /> : <ChevronsLeft size={16} />}
        </button>

        <nav className="flex-1 p-4 space-y-1.5 mt-2">
          <button
            onClick={() => setActiveTab('dashboard')}
            title="Live Dashboard"
            className={`w-full flex items-center ${sidebarCollapsed ? 'justify-center' : 'space-x-3'} px-4 py-3 rounded-md transition-all duration-200 ${
              activeTab === 'dashboard' ? 'bg-blue-700 text-white shadow-md' : 'hover:bg-slate-800 hover:text-white'
            }`}
          >
            <LayoutDashboard size={18} />
            {!sidebarCollapsed && <span className="font-semibold text-sm">Live Dashboard</span>}
          </button>

          <button
            onClick={() => setActiveTab('history')}
            title="Schedule History"
            className={`w-full flex items-center ${sidebarCollapsed ? 'justify-center' : 'space-x-3'} px-4 py-3 rounded-md transition-all duration-200 ${
              activeTab === 'history' ? 'bg-blue-700 text-white shadow-md' : 'hover:bg-slate-800 hover:text-white'
            }`}
          >
            <Calendar size={18} />
            {!sidebarCollapsed && <span className="font-semibold text-sm">Schedule History</span>}
          </button>
        </nav>

        <div className={`p-5 border-t border-slate-800 bg-slate-950/30 flex items-center ${sidebarCollapsed ? 'justify-center' : 'justify-between'}`}>
          <button
            onClick={() => setShowProfile(true)}
            title={user.username}
            className={`flex items-center ${sidebarCollapsed ? '' : 'space-x-3'} min-w-0 hover:bg-slate-800/60 rounded-md -m-1.5 p-1.5 transition-colors text-left`}
          >
            <div className="bg-slate-800 p-2 rounded-md text-blue-400 shrink-0"><User size={16} /></div>
            {!sidebarCollapsed && (
              <div className="min-w-0">
                <p className="text-slate-500 text-[9px] uppercase font-bold tracking-wider">{user.role}</p>
                <p className="font-bold text-slate-200 text-xs truncate">{user.username}</p>
              </div>
            )}
          </button>
          {!sidebarCollapsed && (
            <button
              onClick={() => setUser(null)}
              title="Log out"
              className="text-slate-500 hover:text-red-400 transition-colors shrink-0 ml-2"
            >
              <LogOut size={16} />
            </button>
          )}
        </div>
      </div>

      {showProfile && (
        <ProfileModal
          user={user}
          onClose={() => setShowProfile(false)}
          onLogout={() => { setShowProfile(false); setUser(null); }}
        />
      )}

      {/* MAIN CONTENT AREA */}
      <div className="flex-1 flex flex-col overflow-auto z-10 relative">

{/* Top Header */}
        <header className="bg-white shadow-sm px-8 py-4 flex justify-between items-center sticky top-0 z-20 border-b border-slate-200 shrink-0">
          <div>
            <h2 className="text-lg font-bold text-slate-800">Divisional Overview</h2>
            <p className="text-xs text-slate-500 font-medium">Mumbai Railway Network</p>
          </div>
          <div className="flex space-x-5 items-center">

            {/* Live Active Users Badge */}
            <div className="flex items-center space-x-2 bg-slate-100 px-3 py-1.5 rounded-md border border-slate-200 shadow-sm transition-all duration-300">
              <Users size={14} className="text-blue-600" />
              <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wide">
                <span className="text-blue-700 font-black">{activeUsers}</span> Active
              </span>
            </div>

            <NotificationBell notifications={notifications} onOpen={markAllRead} />

            {/* AI Optimizer Badge */}
            <div className="flex items-center space-x-2 bg-teal-50 px-3 py-1.5 rounded-md border border-teal-200 shadow-sm">
              <span className="w-2 h-2 bg-teal-600 rounded-full animate-pulse"></span>
              <span className="text-[11px] font-bold text-teal-800 uppercase tracking-wide">Optimizer Online</span>
            </div>

          </div>
        </header>

        {activeTab === 'history' ? (
          <div className="flex-1 flex flex-col items-center justify-center animate-in fade-in duration-300">
            <Calendar size={48} className="text-slate-300 mb-4" />
            <h2 className="text-xl font-bold text-slate-700">Schedule History</h2>
            <p className="text-sm text-slate-500 mt-2">Database connection pending backend integration.</p>
          </div>
        ) : (
          <main className="p-6 flex-1 flex flex-col space-y-5 overflow-y-auto">

            {/* KPI RIBBON */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-1 shrink-0">
              <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200 flex items-center space-x-4 border-l-4 border-l-blue-500">
                <div className="bg-slate-50 p-2.5 rounded text-blue-600"><LayoutDashboard size={20} /></div>
                <div><p className="text-[10px] font-bold text-slate-500 uppercase">Active Blocks</p><h4 className="text-lg font-black text-slate-800">{dashboardMetrics.active_blocks}</h4></div>
              </div>
              <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200 flex items-center space-x-4 border-l-4 border-l-red-500">
                <div className="bg-slate-50 p-2.5 rounded text-red-600"><ShieldCheck size={20} /></div>
                <div><p className="text-[10px] font-bold text-slate-500 uppercase">Conflicts Detected</p><h4 className="text-lg font-black text-slate-800">{dashboardMetrics.conflicts}</h4></div>
              </div>
              <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200 flex items-center space-x-4 border-l-4 border-l-teal-500">
                <div className="bg-slate-50 p-2.5 rounded text-teal-600"><Activity size={20} /></div>
                <div><p className="text-[10px] font-bold text-slate-500 uppercase">AI Efficiency</p><h4 className="text-lg font-black text-slate-800">{dashboardMetrics.efficiency}%</h4></div>
              </div>
              <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200 flex items-center space-x-4 border-l-4 border-l-slate-700">
                <div className="bg-slate-50 p-2.5 rounded text-slate-700"><Clock size={20} /></div>
                <div><p className="text-[10px] font-bold text-slate-500 uppercase">Hours Saved</p><h4 className="text-lg font-black text-slate-800">{dashboardMetrics.hours_saved} hrs</h4></div>
              </div>
            </div>

            {/* FILTER TOOLBAR */}
            <div className="bg-white px-5 py-2.5 rounded-lg shadow-sm border border-slate-200 flex justify-between items-center z-10 shrink-0">
              <div className="flex items-center space-x-2 text-slate-700">
                <Filter size={16} />
                <span className="text-xs font-bold uppercase tracking-wide">Data Filter</span>
              </div>
              <select
                value={filterTask}
                onChange={(e) => setFilterTask(e.target.value)}
                className="bg-slate-50 border border-slate-200 text-slate-700 text-xs font-medium rounded-md focus:ring-blue-600 focus:border-blue-600 block p-2 cursor-pointer outline-none"
              >
                <option value="ALL">Show All Scheduled Tasks</option>
                {MAINTENANCE_BLOCKS.map(block => (
                  <option key={block.id} value={block.id}>{block.id}: {block.title} ({block.department})</option>
                ))}
              </select>
            </div>

            {/* ROW 1: THE MACRO VIEW (Fixed Exact Height) */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 h-[450px] shrink-0">
              <div className="bg-white rounded-lg shadow-sm border border-slate-200 overflow-hidden transition-all duration-300 h-full">
                <GanttTimeline selectedBlockId={selectedBlockId} onSelectBlock={setSelectedBlockId} filteredBlocks={displayBlocks} conflicts={conflicts} />
              </div>
              <div className="bg-white rounded-lg shadow-sm border border-slate-200 p-1 transition-all duration-300 h-full">
                <CorridorMap selectedBlockId={selectedBlockId} onSelectBlock={setSelectedBlockId} filteredBlocks={displayBlocks} />
              </div>
            </div>

            {/* ROW 2: THE MICRO VIEW (Minimum Height to prevent squeezing) */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 pb-8 min-h-[420px] shrink-0 items-stretch">
              <div className="lg:col-span-1 h-full">
                <RequestForm onSubmit={handleRequestSubmit} />
              </div>

              {/* Diagnostic Area */}
              <div className="lg:col-span-2 bg-slate-100/50 rounded-lg shadow-inner border border-slate-200 p-6 flex flex-col justify-center items-center relative overflow-hidden h-full">
                <h3 className="absolute top-4 left-5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Diagnostic Engine</h3>

                <div className="w-full max-w-lg mt-4 transition-all duration-500 ease-in-out">
                  {!selectedBlockId && (
                    <div className="text-center py-10 opacity-60">
                      <LayoutDashboard size={40} className="mx-auto text-slate-400 mb-3" />
                      <p className="text-slate-500 text-sm font-medium">Select a block on the timeline or map to run diagnostics.</p>
                    </div>
                  )}

                  {selectedBlockId && isConflict && !isResolved && (
                    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                      <ConflictCard
                        conflictData={{
                          severity: 'critical', type: 'Unsafe Track Overlap', description: `Critical resource and spatial conflict detected at ${selectedBlockData?.sectionId}.`, departments: ['Track', 'Civil'], overlapTime: `${selectedBlockData?.startHour}:00 - ${selectedBlockData?.endHour}:00`
                        }}
                        onRunOptimizer={handleOptimize}
                        isOptimizing={isOptimizing}
                      />
                    </div>
                  )}

                  {selectedBlockId && isResolved && explanationData && (
                    <div className="animate-in fade-in zoom-in-95 duration-500">
                      <ExplanationReceipt
                        explanationData={explanationData}
                      />
                    </div>
                  )}

                  {selectedBlockId && !isConflict && !isResolved && (
                    <div className="bg-white border-l-4 border-l-teal-500 shadow-sm p-5 rounded-r-md text-left mt-6 animate-in fade-in slide-in-from-bottom-4 duration-500 flex items-center space-x-4">
                      <div className="bg-teal-50 p-3 rounded-full"><ShieldCheck size={28} className="text-teal-600" /></div>
                      <div>
                        <h4 className="text-slate-800 font-black text-base">Safe Track Block Verified</h4>
                        <p className="text-slate-500 font-medium text-xs mt-0.5">Block {selectedBlockId} has no conflicts and is cleared for execution.</p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>

          </main>
        )}
      </div>
    </div>
  );
}